# Generated by Django 2.2.7 on 2019-11-16 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logging_errors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='error',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
